frase = 'Curso em Video Python'
# fatiamento
print(frase[9])
print(frase[9:14])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(frase[9::3])
print(len(frase))
print(frase.count('o'))
print(frase.count('o', 0, 13))
print(frase.find('deo'))
print(frase.find('Android'))
print('Curso' in frase)
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.split())
frase2 = '   Aprenda Python  '
print(frase2)
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())
frase3 = 'Curso em Video Python'.split()
print(frase3)
print('-'.join(frase3))

