a = input('Digite algo: ')
print('Tipo primitivo: ', type(a))
print('Espaços: ', a.isspace())
print('Numerico: ', a.isnumeric())
print('Alfanumerico: ', a.isalnum())
print('Alfabetico: ', a.isalpha())
print('Maiusculo: ', a.islower())
print('Minusculo: ', a.isupper())
print('Capitalizado: ', a.istitle())